# .github/ISSUE_TEMPLATE/bug_report.yaml
name: Bug Report
description: File a bug report to help us improve StormDetection.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: "The script crashes when loading a radar image..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "The script should load the radar image and display detections."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Drag and drop images here or paste links."
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: [e.g., Ubuntu 20.04]
        - Python Version: [e.g., 3.8]
        - Dependencies: [e.g., torch==2.0.0]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Any additional details or logs that might help."
    validations:
      required: false 
